server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://***:3306/zj_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 123456
    port: 6379
    password: pwd

mybatis-plus:
#  configuration:
#    # 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除
      logic-delete-field: delFlag
      #删除 1
      logic-delete-value: 1
      #未删除 0
      logic-not-delete-value: 0
      #主键自增
      id-type: auto

#七牛云OSS存储
oss:
  accessKey: accessKey
  secretKey: secretKey
  bucket: bucket